/**
 * [파일 역할]
 * - 애플리케이션의 공통 레이아웃을 정의하는 파일입니다.
 * - 모든 페이지에 공통으로 적용되는 HTML 구조(html, body 태그 등)와 스타일, 폰트 등을 설정합니다.
 */
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
