# Generated by Django 5.2.8 on 2025-12-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='title',
            field=models.CharField(default='소비 코칭', max_length=100),
        ),
    ]
