# Generated by Django 5.2.8 on 2025-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("item", models.CharField(default="", max_length=100)),
                ("store", models.CharField(default="", max_length=100)),
                ("amount", models.IntegerField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_impulsive", models.BooleanField(default=False)),
                ("ai_feedback", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
