# Generated by Django 5.2.8 on 2025-12-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_created_at_transaction_is_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_fixed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_impulsive',
        ),
    ]
