# Generated by Django 5.2.8 on 2025-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
