# Generated by Django 5.1.3 on 2024-11-25 13:00

"""
[파일 역할]
- Django가 models.py를 보고 자동으로 생성한 '첫 번째' DB 설계도입니다.
- 이 파일을 실행(migrate)하면 DB에 실제 테이블이 생성됩니다.
- 주의: 이 파일은 자동으로 생성되므로 직접 수정하지 않는 것이 좋습니다.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
