# Generated by Django 5.2.8 on 2025-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="description",
            new_name="memo",
        ),
        migrations.AddField(
            model_name="transaction",
            name="ai_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_impulsive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="item",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="store",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(max_length=20),
        ),
    ]
